config/routes.rb
Rails.application.routes.draw do
  get 'customer/index'
  # devise_for :users
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do 
    #root 'users/sessions#new'
    root 'customer#index'
  end
  
  scope :loan do
    get 'index', to: 'loans#index'
    get ':id/edit', to: 'loans#edit', as: 'edit_loan'
    patch 'update', to: 'loans#update', as:'update_loan'
    post 'createloan', to: 'loans#create', as: 'create_loan'
    post 'filtro', to:'loans#filtering', as: 'filtering_loan'
    get 'resultado/:date', to:'loans#filtered', as: 'filtered_loan'
    get ':id', to: 'loans#loan', as: 'loan'
    post ':id/:portion/confirm', to: 'loans#confirm_payment', as: 'confirm_payment'
    post ':id/:portion/cancel', to: 'loans#cancel_payment', as: 'cancel_payment'
    delete ':id/delete', to: 'loans#destroy_loan', as: 'destroy_loan'

    get 'angular/json', to: 'loans#json_loans'

    # AngularJS
    get 'api/getcustomerloans/:id', to: 'loans#api_get_customer_loans'
    get 'api/getdates', to: 'loans#api_get_dates'
    post 'api/updatedates', to: 'loans#api_update_dates'
    post 'api/newloan', to: 'loans#api_new_loan'
    patch 'api/editloan', to: 'loans#api_edit_loan'

  end

  scope :customer do 
    get 'index', to: 'customer#index'
    get ':id/edit', to: 'customer#edit', as: 'edit_customer'
    patch 'update', to:'customer#update', as: 'update_customer'
    delete ':id/destroy', to: 'customer#destroy', as: 'destroy_customer'
    post 'createcustomer', to:'customer#create', as: 'create_customer'
    get ':id', to: 'customer#show', as: 'show_customer'
    post 'filtro', to:'customer#filtering', as: 'filtering_customer_loan'
    get 'resultado/:customer_id/:date/', to:'customer#filtered', as: 'filtered_customer_loan'
    get 'resultado/:customer_id/:date/confirm', to: 'customer#confirm_payment', as: 'confirm_customer_payments'
    get 'resultado/:customer_id/:date/cancel', to: 'customer#cancel_payment', as: 'cancel_customer_payments'
    get 'angular/json', to: 'customer#json_customers'
    get 'test/error', to: 'customer#error'
    # AngularJS
    post 'api/createcustomer', to: 'customer#api_create_customer'
    patch 'api/updatecustomer', to: 'customer#api_update_customer'
    get 'api/getcustomer/:id', to: 'customer#api_get_customer'
    get 'api/filter/:id', to: 'customer#api_filter'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord
  # validates :amount,:store, :portion1, :portion2, :portion3, :date_p1, :date_p2, :date_p3, presence: true
  belongs_to :customer
  validates :amount, :portion1, :portion2, :portion3, :store, :date_p1, :date_p2, :date_p3, presence: true
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @loans = Loan.all.order(:date_p1, :date_p2, :date_p3)
    @newLoan = Loan.new
    @p1 = Date.today + 70
    @p2 = Date.today + 100
    @p3 = Date.today + 130
    @loansFilter = loans_filter
  end
  
  def create
    @loan = Loan.new(loans_params)
    if @loan.save
      puts "Salvo com sucesso"
      redirect_to show_customer_path(params[:loan][:customer_id])
    else 
      flash[:notice] = "Não cadastrado."
      redirect_to show_customer_path(params[:loan][:customer_id])
    end
  end

  def edit
    @loan = Loan.find(params[:id])
    @customer_id = Customer.find(@loan.customer_id).id
  end

  def update
    @loan = Loan.find(params[:loan][:id])
    @loan.update(loans_params)
    redirect_to show_customer_path(params[:loan][:customer_id])
  end
  
  def loan 
    @loan = Loan.find(params[:id])
  end
  
  def confirm_payment
    @loan = Loan.find(params[:id])
    if params[:portion].to_i == 1
      @loan.update(paid_p1: true)
      flash[:notice] = "Pagamento confirmado da 1ª parcela"
    elsif  params[:portion].to_i == 2
      @loan.update(paid_p2: true)
      flash[:notice] = "Pagamento confirmado da 2ª parcela"
    elsif params[:portion].to_i == 3
      @loan.update(paid_p3: true)
      flash[:notice] = "Pagamento confirmado da 3ª parcela"
    end
    redirect_to loan_path(params[:id])
  end
  
  def cancel_payment
    @loan = Loan.find(params[:id])
    if params[:portion].to_i == 1
      @loan.update(paid_p1: false)
      flash[:notice] = "Pagamento da 1ª parcela cancelado"
    elsif  params[:portion].to_i == 2
      @loan.update(paid_p2: false)
      flash[:notice] = "Pagamento da 2ª parcela cancelado"
    elsif params[:portion].to_i == 3
      @loan.update(paid_p3: false)
      flash[:notice] = "Pagamento da 3ª parcela cancelado"
    end
    redirect_to loan_path(params[:id])
  end
  
  def filtering
    redirect_to filtered_loan_path(params[:date])
  end
  
  def filtered
    @loansFilter = loans_filter
    @filter = params[:date]
    @loans = Loan.all.select {|loan| (loan.date_p1.month == params[:date][0..1].to_i and loan.date_p1.year == params[:date][3..7].to_i) or 
                                    (loan.date_p2.month == params[:date][0..1].to_i and loan.date_p2.year == params[:date][3..7].to_i) or 
                                    (loan.date_p3.month == params[:date][0..1].to_i and loan.date_p2.year == params[:date][3..7].to_i)
                              }
    @newLoan = Loan.new
    @p1 = Date.today + 30
    @p2 = Date.today + 60
    @p3 = Date.today + 90
  end
  
  def destroy_loan
    @loan = Loan.find(params[:id])
    @customer_id = @loan.customer_id
    if @loan.destroy
      redirect_to show_customer_path(@customer_id)
    end
  end

  # AngularJS
  def json_loans
    @loans = Loan.all
    render json: {status: 200, data: @loans}
  end

  def api_get_customer_loans
    @loans = Loan.all.where(customer_id: params[:id])
    render json: {status: 200, data: @loans}
  end

  def api_get_dates
    @p1 = Date.today + 70
    @p2 = Date.today + 100
    @p3 = Date.today + 130
    render json: { status: 200, data: {date_p1: @p1, date_p2: @p2, date_p3: @p3}}
  end

  def api_update_dates
    @p1 = Date.parse(params[:date_p1])
    @p2 = @p1 + 30
    @p3 = @p1 + 60
    render json: { status: 200, data: {date_p1: @p1, date_p2: @p2, date_p3: @p3}}
  end

  def api_new_loan
    puts params
    @loan = Loan.new
    @loan.store = params[:store]
    @loan.amount = params[:amount]
    @loan.portion1 = params[:portion1]
    @loan.portion2 = params[:portion2]
    @loan.portion3 = params[:portion3]
    @loan.date_p1 = params[:date_p1]
    @loan.date_p2 = params[:date_p2]
    @loan.date_p3 = params[:date_p3]
    @loan.paid_p1 = false
    @loan.paid_p2 = false
    @loan.paid_p3 = false
    @loan.customer_id = params[:customer_id]
    @loan.save
    render json: {status: 200, loanId: @loan.id}
  end

  def api_edit_loan
    @loan = Loan.find(params[:id])
    @loan.store = params[:store]
    @loan.amount = params[:amount]
    @loan.portion1 = params[:portion1]
    @loan.portion2 = params[:portion2]
    @loan.portion3 = params[:portion3]
    @loan.date_p1 = params[:date_p1]
    @loan.date_p2 = params[:date_p2]
    @loan.date_p3 = params[:date_p3]
    @loan.paid_p1 = false
    @loan.paid_p2 = false
    @loan.paid_p3 = false
    @loan.customer_id = params[:customer_id]
    @loan.save
    render json: {status: 200}
  end
  
  private
  
  def loans_params
    params.require(:loan).permit(:customer_id, :amount, :store, :portion1, :portion2, :portion3, :date_p1, :date_p2, :date_p3)
  end
  
  def loans_filter
    @loansYears = []
    Loan.all.each do |loan|
      @loansYears.push(loan.date_p1.year)
      @loansYears.push(loan.date_p2.year)
      @loansYears.push(loan.date_p3.year)
    end
    @loansYears = @loansYears.sort.uniq
    @loansFilter = []
    for i in 0..(@loansYears.length - 1)
      count = 1
      12.times do
        if count < 10
          @loansFilter.push("0#{count}/#{@loansYears[i]}")
        else
          @loansFilter.push("#{count}/#{@loansYears[i]}")
        end
        count += 1
      end
    end
    @loansFilter
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/edit.html.erb
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
    </section>
    <section class="content">
      <div class="box box-primary" id="">
        <div class="box-header with-border">
          <h3 class="box-title">Editar Emprestimo</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <%= form_with  model: @loan, url: '/loan/update' do |f| %>
              <!-- text input -->
              <div class='d-none'>
                <%= f.text_field :customer_id, class:'form-control clear-field', value: @customer_id%>
                <%= f.text_field :id, class:'form-control clear-field', value: @loan.id%>
              </div>
              <div class="form-group">
                <label>Loja</label>
                <%= f.text_field :store, class:'form-control clear-field'%>
              </div>
              <div class="form-group">
                <label>Valor</label>
                <%= f.text_field :amount, class:'form-control clear-field'%>
              </div>
              <div class="form-group">
                <div class='row'>
                  <div class='col-md-3'>
                    <label>Parcela 1</label>
                    <%= f.text_field :portion1, class:'form-control clear-field'%>
                  </div>
                  <div class='col-md-3'>
                    <label>Pagamento da 1ª parcela</label>
                    <%= f.text_field :date_p1, class:'form-control', value: @loan.date_p1.strftime('%d/%m/%Y'), id:'date_p1'%>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class='row'>
                  <div class='col-md-3'>
                    <label>Parcela 2</label>
                    <%= f.text_field :portion2, class:'form-control clear-field'%>
                  </div>
                  <div class='col-md-3'>
                    <label>Pagamento da 2ª parcela</label>
                    <%= f.text_field :date_p2, class:'form-control', value: @loan.date_p2.strftime('%d/%m/%Y'), id:'date_p2'%>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class='row'>
                  <div class='col-md-3'>
                    <label>Parcela 3</label>
                    <%= f.text_field :portion3, class:'form-control clear-field'%>
                  </div>
                  <div class='col-md-3'>
                    <label>Pagamento da 3ª parcela</label>
                    <%= f.text_field :date_p3, class:'form-control', value: @loan.date_p3.strftime('%d/%m/%Y'), id:'date_p3'%>
                  </div>
                </div>
              </div>
              <div class="box-footer">
                <%= f.submit "Salvar", class:'btn btn-primary', id:'new-loan-submit'%>
                <%= link_to 'Voltar', show_customer_path(@customer_id), class:'btn btn-danger'%>
              </div>
            <% end %>
          </div>
    </section>
</div>

app/views/loans/filtered.html.erb
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
      
    </section>
 
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class='col-md-4'>
          <button class='btn btn-primary' id='new-loan' style="margin-bottom: 5px">Novo Emprestimo</button>
          <button class='btn btn-danger d-none' id='cancel-loan' style="margin-bottom: 5px">Cancelar</button>
        </div>
        <div class='col-md-4'>
          <p>Filtro: <%= @filter %></p>
        </div>
        
        <div class='col-md-4'>
          <%= form_with url: '/loan/filtro', remote: false do |f| %>
            <%= f.select :date, @filter, class:'form-control'%>
            <%= f.submit 'Filtrar', class:'btn btn-primary btn-sm'%>
          <% end %>
        </div>
      </div>
      <div class="box box-primary d-none" id="new-loan-form">
        <div class="box-header with-border">
          <h3 class="box-title">Novo Emprestimo</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <%= form_with  model: @newLoan, url: '/loan/createloan' do |f| %>
            <!-- text input -->
            <div class="form-group">
              <label>Nome</label>
              <%= f.text_field :name, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>Loja</label>
              <%= f.text_field :store, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>Valor</label>
              <%= f.text_field :amount, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <div class='row'>
                <div class='col-md-3'>
                  <label>Parcela 1</label>
                  <%= f.text_field :portion1, class:'form-control clear-field'%>
                </div>
                <div class='col-md-3'>
                  <label>Pagamento da 1ª parcela</label>
                  <%= f.text_field :date_p1, class:'form-control', value: @p1.strftime('%d/%m/%Y'), id:'date_p1'%>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class='row'>
                <div class='col-md-3'>
                  <label>Parcela 2</label>
                  <%= f.text_field :portion2, class:'form-control clear-field'%>
                </div>
                <div class='col-md-3'>
                  <label>Pagamento da 2ª parcela</label>
                  <%= f.text_field :date_p2, class:'form-control', value: @p2.strftime('%d/%m/%Y'), id:'date_p2'%>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class='row'>
                <div class='col-md-3'>
                  <label>Parcela 3</label>
                  <%= f.text_field :portion3, class:'form-control clear-field'%>
                </div>
                <div class='col-md-3'>
                  <label>Pagamento da 3ª parcela</label>
                  <%= f.text_field :date_p3, class:'form-control', value: @p3.strftime('%d/%m/%Y'), id:'date_p3'%>
                </div>
              </div>
            </div>
            <div class="box-footer">
              <%= f.submit "Cadastrar", class:'btn btn-primary', id:'new-loan-submit'%>
            </div>
            
          <% end %>
        </div>
      </div>
      <!-- Main row -->
      <div class="row">
        <div class='col-md-12'>
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Emprestimos</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-striped">
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Nome</th>
                  <th>Loja</th>
                  <th>Valor</th>
                  <th>1ª Parcela</th>
                  <th>2ª Parcela</th>
                  <th>3ª Parcela</th>
                </tr>
                <% @count = 1%>
                <% if !@loans.nil?%>
                  <% @loans.each do |loan| %>
                    <tr style="font-weight: normal">
                      <td><%= @count %>.</td>
                      <% @count += 1 %>
                      <td><%= link_to loan.name, loan_path(loan.id) %></td>
                      <td><%= loan.store%></td>
                      <td>R$ <%= loan.amount%></td>
                      <% if loan.paid_p1 %>
                        <td><span class='text-success'>R$ <%= loan.portion1%> (<%= loan.date_p1.strftime('%d/%m/%Y')%>)</span></td>
                      <% else %>
                        <td><span class='text-danger'>R$ <%= loan.portion1%> (<%= loan.date_p1.strftime('%d/%m/%Y')%>)</span></td>
                      <% end %>
                      <% if loan.paid_p2 %>
                        <td><span class='text-success'>R$ <%= loan.portion2%> (<%= loan.date_p2.strftime('%d/%m/%Y')%>)</span></td>
                      <% else %>
                        <td><span class='text-danger'>R$ <%= loan.portion2%> (<%= loan.date_p2.strftime('%d/%m/%Y')%>)</span></td>
                      <% end %>
                      <% if loan.paid_p3 %>
                        <td><span class='text-success'>R$ <%= loan.portion3%> (<%= loan.date_p3.strftime('%d/%m/%Y')%>)</span></td>
                      <% else %>
                      <td><span class='text-danger'>R$ <%= loan.portion3%> (<%= loan.date_p3.strftime('%d/%m/%Y')%>)</span></td>
                      <% end %>
                    </tr>
                  <% end %>
                <% end %>
                <tr>
                  <td><b>Total</b></td>
                  <td></td>
                  <td></td>
                  <td>R$ <%= @loans.sum{ |loan| loan.amount }%></td>
                  <td>R$ <%= @loans.select{ |loan| !loan.paid_p1 }.sum{ |loan| loan.portion1 }%></td>
                  <td>R$ <%= @loans.select{ |loan| !loan.paid_p2 }.sum{ |loan| loan.portion2 }%></td>
                  <td>R$ <%= @loans.select{ |loan| !loan.paid_p3 }.sum{ |loan| loan.portion3 }%></td>
                </tr>
              </table>
            </div>
        </div>
      </div>
      <!-- /.row (main row) -->
    </section>
    <!-- /.content -->
  </div>

app/views/loans/index.html.erb
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
    </section>
 
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class='col-md-8'>
          <button class='btn btn-primary' id='new-loan' style="margin-bottom: 5px">Novo Emprestimo</button>
          <button class='btn btn-danger d-none' id='cancel-loan' style="margin-bottom: 5px">Cancelar</button>
        </div>
        <div class='col-md-4'>
          <%= form_with url: '/loan/filtro', remote: false do |f| %>
            <%= f.select :date, @loansFilter, class:'form-control'%>
            <%= f.submit 'Filtrar', class:'btn btn-primary btn-sm'%>
          <% end %>
        </div>
      </div>
      <div class="box box-primary d-none" id="new-loan-form">
        <div class="box-header with-border">
          <h3 class="box-title">Novo Emprestimo</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <%= form_with  model: @newLoan, url: '/loan/createloan' do |f| %>
            <!-- text input -->
            <div class="form-group">
              <label>Nome</label>
              <%= f.text_field :name, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>Loja</label>
              <%= f.text_field :store, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>Valor</label>
              <%= f.text_field :amount, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <div class='row'>
                <div class='col-md-3'>
                  <label>Parcela 1</label>
                  <%= f.text_field :portion1, class:'form-control clear-field'%>
                </div>
                <div class='col-md-3'>
                  <label>Pagamento da 1ª parcela</label>
                  <%= f.text_field :date_p1, class:'form-control', value: @p1.strftime('%d/%m/%Y'), id:'date_p1'%>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class='row'>
                <div class='col-md-3'>
                  <label>Parcela 2</label>
                  <%= f.text_field :portion2, class:'form-control clear-field'%>
                </div>
                <div class='col-md-3'>
                  <label>Pagamento da 2ª parcela</label>
                  <%= f.text_field :date_p2, class:'form-control', value: @p2.strftime('%d/%m/%Y'), id:'date_p2'%>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class='row'>
                <div class='col-md-3'>
                  <label>Parcela 3</label>
                  <%= f.text_field :portion3, class:'form-control clear-field'%>
                </div>
                <div class='col-md-3'>
                  <label>Pagamento da 3ª parcela</label>
                  <%= f.text_field :date_p3, class:'form-control', value: @p3.strftime('%d/%m/%Y'), id:'date_p3'%>
                </div>
              </div>
            </div>
            <div class="box-footer">
              <%= f.submit "Cadastrar", class:'btn btn-primary', id:'new-loan-submit'%>
            </div>
            
          <% end %>
        </div>
      </div>
      <!-- Main row -->
      <div class="row">
        <div class='col-md-12'>
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Emprestimos</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-striped">
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Nome</th>
                  <th>Loja</th>
                  <th>Valor</th>
                  <th>1ª Parcela</th>
                  <th>2ª Parcela</th>
                  <th>3ª Parcela</th>
                  <th>Opções</th>
                </tr>
                <% @count = 1%>
                <% @loans.each do |loan| %>
                <tr style="font-weight: normal">
                  <td><%= @count %>.</td>
                  <% @count += 1 %>
                  <td><%= link_to loan.name, loan_path(loan.id)%></td>
                  <td><%= loan.store%></td>
                  <td>R$ <%= loan.amount%></td>
                  <% if loan.paid_p1 %>
                    <td><span class='text-success'>R$ <%= loan.portion1%> (<%= loan.date_p1.strftime('%d/%m/%Y')%>)</span></td>
                  <% else %>
                    <td><span class='text-danger'>R$ <%= loan.portion1%> (<%= loan.date_p1.strftime('%d/%m/%Y')%>)</span></td>
                  <% end %>
                  <% if loan.paid_p2 %>
                    <td><span class='text-success'>R$ <%= loan.portion2%> (<%= loan.date_p2.strftime('%d/%m/%Y')%>)</span></td>
                  <% else %>
                    <td><span class='text-danger'>R$ <%= loan.portion2%> (<%= loan.date_p2.strftime('%d/%m/%Y')%>)</span></td>
                  <% end %>
                  <% if loan.paid_p3 %>
                    <td><span class='text-success'>R$ <%= loan.portion3%> (<%= loan.date_p3.strftime('%d/%m/%Y')%>)</span></td>
                  <% else %>
                  <td><span class='text-danger'>R$ <%= loan.portion3%> (<%= loan.date_p3.strftime('%d/%m/%Y')%>)</span></td>
                  <% end %>
                  <td><%= link_to "Apagar", destroy_loan_path(loan.id), class:'btn btn-danger btn-sm btn-rounded', method: :delete, data: {confirm: 'Tem certeza que deseja apagar o emprestimo?'}%></td>
                </tr>
                <% end %>
                <tr>
                  <td><b>Total</b></td>
                  <td></td>
                  <td></td>
                  <td>R$ <%= @loans.sum{ |loan| loan.amount }%></td>
                  <td>R$ <%= @loans.select{ |loan| !loan.paid_p1 }.sum{ |loan| loan.portion1 }%></td>
                  <td>R$ <%= @loans.select{ |loan| !loan.paid_p2 }.sum{ |loan| loan.portion2 }%></td>
                  <td>R$ <%= @loans.select{ |loan| !loan.paid_p3 }.sum{ |loan| loan.portion3 }%></td>
                  <td></td>
                </tr>
              </table>
            </div>
        </div>
      </div>
      <!-- /.row (main row) -->
    </section>
    <!-- /.content -->
  </div>

app/views/loans/loan.html.erb
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
    </section>
    <section class="content">
      <div class="row">
        <div class='col-md-12'>
          <% if flash[:notice] %>
            <%= flash[:notice] %>
          <% end %>
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Emprestimo</h3>
            </div>
            <div class="box-body">
              <table class="table table-striped">
                <tr>
                  <th style="width: 10px">#</th>
                  
                  <th>Loja</th>
                  <th>Valor</th>
                  <th>1ª Parcela</th>
                  <th>2ª Parcela</th>
                  <th>3ª Parcela</th>
                </tr>
                <tr style="font-weight: normal">
                  <td>1</td>
                  
                  <td><%= @loan.store %></td>
                  <td><%= @loan.amount %></td>
                  <% if @loan.paid_p1 %>
                    <td><span class='text-success'><%= @loan.portion1 %> (<%= @loan.date_p1.strftime('%d/%m/%Y')%>)</span></td>
                  <% else %>
                    <td><span class='text-danger'><%= @loan.portion1 %> (<%= @loan.date_p1.strftime('%d/%m/%Y')%>)</span></td>
                  <% end %>
                  <% if @loan.paid_p2 %>
                    <td><span class='text-success'><%= @loan.portion2 %> (<%= @loan.date_p2.strftime('%d/%m/%Y')%>)</span></td>
                  <% else %>
                    <td><span class='text-danger'><%= @loan.portion2 %> (<%= @loan.date_p2.strftime('%d/%m/%Y')%>)</span></td>
                  <% end %>
                  <% if @loan.paid_p3 %>
                    <td><span class='text-success'><%= @loan.portion3 %> (<%= @loan.date_p3.strftime('%d/%m/%Y')%>)</span></td>
                  <% else %>
                    <td><span class='text-danger'><%= @loan.portion3 %> (<%= @loan.date_p3.strftime('%d/%m/%Y')%>)</span></td>
                  <% end %>
                </tr>
                <tr>
                  
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>
                      <%= link_to 'Confirmar', confirm_payment_path(@loan.id, 1), method: :post, data: {confirm: 'Tem certeza que deseja confirmar o pagamento?'}, class:'btn btn-success btn-sm'%>
                      <%= link_to 'Cancelar', cancel_payment_path(@loan.id, 1), method: :post, data: {confirm: 'Tem certeza que deseja cancelar o pagamento?'}, class:'btn btn-danger btn-sm' %>
                  </td>
                  <td>
                    <%= link_to 'Confirmar', confirm_payment_path(@loan.id, 2), method: :post, data: {confirm: 'Tem certeza que deseja confirmar o pagamento?'}, class:'btn btn-success btn-sm'%>
                    <%= link_to 'Cancelar', cancel_payment_path(@loan.id, 2), method: :post, data: {confirm: 'Tem certeza que deseja cancelar o pagamento?'}, class:'btn btn-danger btn-sm' %>
                  </td>
                  <td>
                    <%= link_to 'Confirmar', confirm_payment_path(@loan.id, 3), method: :post, data: {confirm: 'Tem certeza que deseja confirmar o pagamento?'}, class:'btn btn-success btn-sm'%>
                    <%= link_to 'Cancelar', cancel_payment_path(@loan.id, 3), method: :post, data: {confirm: 'Tem certeza que deseja cancelar o pagamento?'}, class:'btn btn-danger btn-sm' %>
                  </td>
                </tr>
              </table>
              <%= link_to 'Voltar', show_customer_path(@loan.customer.id), class:'btn btn-primary btn-sm'%>
            </div>
          </div>
        </div>
      </div>
    </section>