config/routes.rb
Rails.application.routes.draw do
  get 'customer/index'
  # devise_for :users
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do 
    #root 'users/sessions#new'
    root 'customer#index'
  end
  
  scope :loan do
    get 'index', to: 'loans#index'
    get ':id/edit', to: 'loans#edit', as: 'edit_loan'
    patch 'update', to: 'loans#update', as:'update_loan'
    post 'createloan', to: 'loans#create', as: 'create_loan'
    post 'filtro', to:'loans#filtering', as: 'filtering_loan'
    get 'resultado/:date', to:'loans#filtered', as: 'filtered_loan'
    get ':id', to: 'loans#loan', as: 'loan'
    post ':id/:portion/confirm', to: 'loans#confirm_payment', as: 'confirm_payment'
    post ':id/:portion/cancel', to: 'loans#cancel_payment', as: 'cancel_payment'
    delete ':id/delete', to: 'loans#destroy_loan', as: 'destroy_loan'

    get 'angular/json', to: 'loans#json_loans'

    # AngularJS
    get 'api/getcustomerloans/:id', to: 'loans#api_get_customer_loans'
    get 'api/getdates', to: 'loans#api_get_dates'
    post 'api/updatedates', to: 'loans#api_update_dates'
    post 'api/newloan', to: 'loans#api_new_loan'
    patch 'api/editloan', to: 'loans#api_edit_loan'

  end

  scope :customer do 
    get 'index', to: 'customer#index'
    get ':id/edit', to: 'customer#edit', as: 'edit_customer'
    patch 'update', to:'customer#update', as: 'update_customer'
    delete ':id/destroy', to: 'customer#destroy', as: 'destroy_customer'
    post 'createcustomer', to:'customer#create', as: 'create_customer'
    get ':id', to: 'customer#show', as: 'show_customer'
    post 'filtro', to:'customer#filtering', as: 'filtering_customer_loan'
    get 'resultado/:customer_id/:date/', to:'customer#filtered', as: 'filtered_customer_loan'
    get 'resultado/:customer_id/:date/confirm', to: 'customer#confirm_payment', as: 'confirm_customer_payments'
    get 'resultado/:customer_id/:date/cancel', to: 'customer#cancel_payment', as: 'cancel_customer_payments'
    get 'angular/json', to: 'customer#json_customers'
    get 'test/error', to: 'customer#error'
    # AngularJS
    post 'api/createcustomer', to: 'customer#api_create_customer'
    patch 'api/updatecustomer', to: 'customer#api_update_customer'
    get 'api/getcustomer/:id', to: 'customer#api_get_customer'
    get 'api/filter/:id', to: 'customer#api_filter'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :loans, dependent: :destroy

	validates :name, presence: true
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_action :authenticate_user!
  def index
  	# @customer = Customer.all.order(:name).limit(1)
    @newCustomer = Customer.new
    @p1 = Date.today + 70
    @p2 = Date.today + 100
    @p3 = Date.today + 130
  end

  def create
  	@customer = Customer.new(customer_params)
  	@customer.save
    redirect_to root_path
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:customer][:id])
    @customer.update(customer_params)
    redirect_to root_path
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to root_path
  end

  def show
  	@customer = Customer.find(params[:id])
    @filter = filter(params[:id])
    @newLoan = Loan.new
    @p1 = Date.today + 70
    @p2 = Date.today + 100
    @p3 = Date.today + 130
  end

  def filtering
    redirect_to filtered_customer_loan_path(params[:customer_id], params[:date])
  end
  
  def filtered
    # 01/2020
    # 01234567
    @mes = params[:date][0..1]
    @ano = params[:date][3..6]
      @customer_id = params[:customer_id]
    @cliente = Customer.find(params[:customer_id])
    @filter = params[:date]
    # Retorna os emprestimos filtrados
    @loans = selecting_loans(params[:date], params[:customer_id])
  end

  def confirm_payment
    @loans = selecting_loans(params[:date], params[:customer_id])
    @loans.each do |loan|
      if loan.date_p1.month == params[:date][0..1].to_i and loan.date_p1.year == params[:date][3..7].to_i
        loan.update(paid_p1: true)
      end
      if loan.date_p2.month == params[:date][0..1].to_i and loan.date_p2.year == params[:date][3..7].to_i
        loan.update(paid_p2: true)
      end 
      if loan.date_p3.month == params[:date][0..1].to_i and loan.date_p3.year == params[:date][3..7].to_i
        loan.update(paid_p3: true)
      end        
    end
    redirect_to filtered_customer_loan_path(params[:customer_id], params[:date])
  end

  def cancel_payment
    @loans = selecting_loans(params[:date], params[:customer_id])
    @loans.each do |loan|
      if loan.date_p1.month == params[:date][0..1].to_i and loan.date_p1.year == params[:date][3..7].to_i
        loan.update(paid_p1: false)
      end
      if loan.date_p2.month == params[:date][0..1].to_i and loan.date_p2.year == params[:date][3..7].to_i
        loan.update(paid_p2: false)
      end 
      if loan.date_p3.month == params[:date][0..1].to_i and loan.date_p3.year == params[:date][3..7].to_i
        loan.update(paid_p3: false)
      end        
    end
    redirect_to filtered_customer_loan_path(params[:customer_id], params[:date])
  end

  def error
    raise 'boom'
    render plain: "Hello World"
  end

  # AngularJS
  def json_customers
    if params[:name] != nil
      @customers = Customer.where("lower(name) like ?", params[:name].downcase << "%").order(:name).limit(10)
    elsif params[:page] != nil
      @customers = Customer.all.order(:name).limit(10).offset(10*(params[:page].to_i))
    else
      @customers = Customer.all.order(:name).limit(10).offset(0)
    end
    render json:{status: 200, data: @customers}
  end

  def api_create_customer
    @customer = Customer.new
    @customer.name = params[:name]
    @customer.cpf = params[:cpf]
    @customer.address = params[:address]
    @customer.phone = params[:phone]
    if @customer.save
      render json: {status: 200, data: @customer.id}
    end
  end

  def api_update_customer
    @customer = Customer.find(params[:id])
    @customer.name = params[:name]
    @customer.cpf = params[:cpf]
    @customer.address = params[:address]
    @customer.phone = params[:phone]
    @customer.save
  end

  def api_get_customer
    @customer = Customer.find(params[:id])
    render json: {status: 200, data: @customer}
  end

  def api_filter
    @filter = filter(params[:id])
    render json: { status: 200, data: @filter}
  end



  private

  def customer_params
  	params.require(:customer).permit(:name, :cpf, :address, :phone)
  end


  def filter(id)
    @loans = Customer.find(id).loans
    @monthArray = []
    @loans.each do |loan|
      if loan.date_p1.month.to_s.length == 1  
        @monthArray.push('0' + loan.date_p1.month.to_s + '/' + loan.date_p1.year.to_s) 
      else
        @monthArray.push(loan.date_p1.month.to_s + '/' + loan.date_p1.year.to_s) 
      end
      if loan.date_p2.month.to_s.length == 1  
        @monthArray.push('0' + loan.date_p2.month.to_s + '/' + loan.date_p2.year.to_s) 
      else
        @monthArray.push(loan.date_p2.month.to_s + '/' + loan.date_p2.year.to_s) 
      end
      if loan.date_p3.month.to_s.length == 1  
        @monthArray.push('0' + loan.date_p3.month.to_s + '/' + loan.date_p3.year.to_s) 
      else
        @monthArray.push(loan.date_p3.month.to_s + '/' + loan.date_p3.year.to_s) 
      end
    end
    # 01/2020
    # 0123456
    @monthArrayUniq = @monthArray.uniq

    return @monthArrayUniq.sort { |a,b| Date.new(b[3..6].to_i, b[0..1].to_i, 01) <=> Date.new(a[3..6].to_i, a[0..1].to_i, 01)}
  end

  def selecting_loans(date, id)
    @loans = Loan.select {|loan| loan.customer_id == id.to_i}
    @loans = @loans.select {|loan| (loan.date_p1.month == date[0..1].to_i and loan.date_p1.year == date[3..7].to_i) or 
                                    (loan.date_p2.month == date[0..1].to_i and loan.date_p2.year == date[3..7].to_i) or 
                                    (loan.date_p3.month == date[0..1].to_i and loan.date_p3.year == date[3..7].to_i)
                              }

    return @loans
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/edit.html.erb
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
    </section>
    <section class="content">
    <div class="box box-primary" id="">
        <div class="box-header with-border">
          <h3 class="box-title">Editar Cliente</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <%= form_with  model: @customer, url: '/customer/update' do |f| %>
            <!-- text input -->
            <div class="form-group d-none">
              <label>Nome</label>
              <%= f.text_field :id, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>Nome</label>
              <%= f.text_field :name, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>CPF</label>
              <%= f.text_field :cpf, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>Endereço</label>
              <%= f.text_field :address, class:'form-control clear-field'%>
            </div>
            <div class="form-group">
              <label>Telefone</label>
              <%= f.text_field :phone, class:'form-control clear-field'%>
            </div>
            <div class="box-footer">
              <%= f.submit "Salvar", class:'btn btn-primary', id:'new-loan-submit', id:'new-customer-submit'%>
              <%= link_to 'Voltar', show_customer_path(@customer.id), class:'btn btn-danger'%>
            </div>
            
          <% end %>
        </div>
      </div>
    </section>
</div>

app/views/customer/filtered.html.erb
   <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
      
    </section>
 
    <!-- Main content -->
    <section class="content">
      <div class="row">
        
        <div class='col-md-4'>
          <h2>Mês: <%= @filter %></h2>
        </div>
        <div class='col-md-4'>
          <h2>Cliente: <%= @cliente.name %></h2>
        </div>
        
      </div>
      
      <!-- Main row -->
      <div class="row">
        <div class='col-md-12'>
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Emprestimos</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-striped">
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Loja</th>
                  <th>Valor</th>
                  <th>Parcela</th>
                </tr>
                <% @count = 1%>
                <% if !@loans.nil?%>
                  <% @loans.each do |loan|%>
                    <% if (loan.date_p1.month == @mes.to_i and loan.date_p1.year == @ano.to_i)%>
                      <tr style='font-weight: normal'>
                        <td><%= @count%></td>
                        <td><%= loan.store%></td>
                        <% if loan.paid_p1 %>
                          <td class='text-green'>R$ <%= loan.portion1.round(2)%> (<%= loan.date_p1.strftime('%d/%m/%y')%>)</td>
                        <% else %>
                          <td class='text-red'>R$ <%= loan.portion1.round(2)%> (<%= loan.date_p1.strftime('%d/%m/%y')%>)</td>
                        <% end %>
                        <td>Parcela 1</td>
                        <% @count += 1%>
                      </tr>
                    <% end %>
                    <% if (loan.date_p2.month == @mes.to_i and loan.date_p2.year == @ano.to_i)%>
                      <tr style='font-weight: normal'>
                        <td><%= @count%></td>
                        <td><%= loan.store%></td>
                         <% if loan.paid_p2 %>
                          <td class='text-green'>R$ <%= loan.portion2.round(2)%> (<%= loan.date_p2.strftime('%d/%m/%y')%>)</td>
                        <% else %>
                          <td class='text-red'>R$ <%= loan.portion2.round(2)%> (<%= loan.date_p2.strftime('%d/%m/%y')%>)</td>
                        <% end %>
                        <td>Parcela 2</td>
                        <% @count += 1%>
                      </tr>
                    <% end %>
                    
                    <% if (loan.date_p3.month == @mes.to_i and loan.date_p3.year == @ano.to_i)%>
                      <tr style='font-weight: normal'>
                        <td><%= @count%></td>
                        <td><%= loan.store%></td>
                         <% if loan.paid_p3 %>
                          <td class='text-green'>R$ <%= loan.portion3.round(2)%> (<%= loan.date_p3.strftime('%d/%m/%y')%>)</td>
                        <% else %>
                          <td class='text-red'>R$ <%= loan.portion3.round(2)%> (<%= loan.date_p3.strftime('%d/%m/%y')%>)</td>
                        <% end %>
                        <td>Parcela 3</td>
                        <% @count += 1%>
                      </tr>
                    <% end %>
                  <% end %>
                <% end%>
                <tr>
                  <% @sum_p1 = @loans.select{ |loan| (loan.date_p1.month == @mes.to_i and loan.date_p1.year == @ano.to_i) }.sum{ |loan| loan.portion1 }%>
                  <% @sum_p2 = @loans.select{ |loan| (loan.date_p2.month == @mes.to_i and loan.date_p2.year == @ano.to_i) }.sum{ |loan| loan.portion2 }%>
                  <% @sum_p3 = @loans.select{ |loan| (loan.date_p3.month == @mes.to_i and loan.date_p3.year == @ano.to_i) }.sum{ |loan| loan.portion3 }%>
                  <td>Total:</td>
                  <td></td>
                  <td>R$ <%= (@sum_p1 + @sum_p2 + @sum_p3).round(2) %></td>
                  <td></td>
                </tr>
              </table>
              <hr>
              <%= link_to 'Confirmar Pagamentos', confirm_customer_payments_path(@customer_id, @mes + '/' + @ano), class: 'btn btn-success', data: {confirm: 'Tem certeza que deseja confirmar todos estes pagamentos?'}%>
              <%= link_to 'Desconfirmar Pagamentos', cancel_customer_payments_path(@customer_id), class: 'btn btn-danger', data: {confirm: 'Tem certeza que deseja desconfirmar todos estes pagamentos?'}%>
              <%= link_to 'Voltar', show_customer_path(@customer_id), class: 'btn btn-primary'%>
            </div>

        </div>
      </div>
      <!-- /.row (main row) -->
    </section>
    <!-- /.content -->
  </div>

app/views/customer/index.html.erb
<div class="content-wrapper" ng-controller="customerIndexCtrl">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
    </section>
 
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class='col-md-8'>
          <button class='btn btn-primary' id='newCustomer' style="margin-bottom: 5px" ng-click="showFormFunction()" ng-show="!showForm">Novo Cliente</button>
        </div>
        <div class="col-md-12">
          <div class="box box-primary" ng-show="showForm">
            <div class="box-header with-border">
              <h3 class="box-title">Novo Cliente</h3>
            </div>
            <div class="box-body">
              <p>Nome</p>
              <input class="form-control" ng-model="customer.name">
              <p>CPF</p>
              <input class="form-control" ng-model="customer.cpf">
              <p>Endereço</p>
              <input class="form-control" ng-model="customer.address">
              <p>Telefone</p>
              <input class="form-control" ng-model="customer.phone">
            </div>
            <div class="box-footer">
              <button class="btn btn-primary" ng-click="addCustomer(customer)">Cadastrar</button>
              <button class='btn btn-danger' ng-click="cancelAddCustomer()">Cancelar</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="ExemploModalCentralizado" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="TituloModalCentralizado">Editar Cliente</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Fechar" ng-click="cancelEditCustomer()">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Nome</p>
              <input class="form-control" ng-model="customerEdit.name">
              <p>CPF</p>
              <input class="form-control" ng-model="customerEdit.cpf">
              <p>Endereço</p>
              <input class="form-control" ng-model="customerEdit.address">
              <p>Telefone</p>
              <input class="form-control" ng-model="customerEdit.phone">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal" ng-click="cancelEditCustomer()">Fechar</button>
              <button type="button" class="btn btn-primary" ng-click="editSaveCustomer(customerEdit)" data-dismiss="modal">Salvar mudanças</button>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="form-group">
        <input class="form-control" placeholder="Digite o nome do cliente..." ng-model="search" ng-keyup="helloWorld()">
      </div>
      <hr>
      <!-- Main row -->
      <div class="row">
        <div class='col-md-12'>
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Clientes</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-striped">
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Nome</th>
<!--                  <th>Valor a receber</th>-->
                  <th>Informações</th>
                </tr>
                <tr ng-repeat="customer in customers" style="font-weight: normal;">
                  <td>{{$index+1}}</td>
                  <td>{{customer.name}}</td>
<!--                  <td>R${{customer.vlrReceber | number: 2}}</td>-->
                  <td>
                    <a href="/customer/{{customer.id}}" class="btn btn-primary btn-sm">Ver Emprestimos</a>
                    <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#ExemploModalCentralizado" ng-click="editCustomer(customer)")>Editar Cliente</button>
                    <a href="/customer/{{customer.id}}/destroy" data-method="delete" data-confirm="Tem certeza que deseja apagar o cliente: {{customer.name}}" class="btn btn-danger btn-sm">Apagar Cliente</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row (main row) -->
      <button class="btn btn-primary btn-sm" ng-click="prevPage()">Voltar página</button>
      <button class="btn btn-default btn-sm">{{page+1}}</button>
      <button class="btn btn-primary btn-sm" ng-click="nextPage()">Próxima página</button>
    </section>
  <!-- /.content -->
</div>

app/views/customer/show.html.erb
<div class="content-wrapper" ng-controller="customerShowCtrl">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Painel de Controle
      </h1>
    </section>
    <section class="content">
      <div class="row">
        <div class='col-md-12'>
          <div class='row'>
            <div class='col-md-6'>
              <button class='btn btn-primary' ng-click="newLoan()" ng-show="!showNewLoanForm">Novo Emprestimo</button>
              <button class='btn btn-danger d-none' id='cancel-loan' >Cancelar</button>
            </div>
            <div class='col-md-6'>
              <div class="form-inline">
                <select ng-options="opt for opt in filterOptions" ng-model="filter" class="form-control inline"></select>
                <a class="btn btn-primary" href="/customer/resultado/{{customerId}}/{{filter.substring(0,2)}}%2F{{filter.substring(3,7)}}">Filtrar</a>
              </div>
            </div>
          </div>
          <!-- New Loan Form -->
          <div class="box box-primary" ng-show="showNewLoanForm">
            <div class="box-header with-border">
              <h3 class="box-title">Novo Emprestimo</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <label>Loja</label>
                <input type="text" class="form-control" ng-model="newLoanObj.store">

                <label>Valor</label>
                <input type="text" class="form-control" ng-model="newLoanObj.amount" ng-blur="calculoDeParcelas(newLoanObj, 1)">
                <div class="row">
                  <div class="col-md-3">
                    <label>Parcela 1</label>
                    <input type="text" class="form-control" ng-model="newLoanObj.portion1">
                  </div>
                  <div class="col-md-3">
                    <label>Previsão de Pagamento da 1ª Parcela</label>
                    <input type="date" class="form-control" ng-model="newLoanObj.date_p1" ng-blur="updateDates(newLoanObj)">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-3">
                    <label>Parcela 2</label>
                    <input type="text" class="form-control" ng-model="newLoanObj.portion2">
                  </div>
                  <div class="col-md-3">
                    <label>Previsão de Pagamento da 2ª Parcela</label>
                    <input type="date" class="form-control" ng-model="newLoanObj.date_p2">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-3">
                    <label>Parcela 3</label>
                    <input type="text" class="form-control" ng-model="newLoanObj.portion3">
                  </div>
                  <div class="col-md-3">
                    <label>Previsão de Pagamento da 3ª Parcela</label>
                    <input type="date" class="form-control" ng-model="newLoanObj.date_p3">
                  </div>
                </div>
              </div>
            </div>
            <div class="box-footer">
              <button class="btn btn-primary" ng-click="submitNewLoan(newLoanObj)">Cadastrar</button>
              <button class="btn btn-danger" ng-click="cancelNewLoan()">Cancelar</button>
            </div>
          </div>
          <!-- End of New Loan Form -->
          <!-- Edit Loan Form -->
          <div class="box box-primary" ng-show="showEditLoanForm">
            <div class="box-header with-border">
              <h3 class="box-title">Novo Emprestimo</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <label>Loja</label>
                <input type="text" class="form-control" ng-model="editLoanObj.store">

                <label>Valor</label>
                <input type="text" class="form-control" ng-model="editLoanObj.amount" ng-blur="calculoDeParcelas(editLoanObj, 2)">
                <div class="row">
                  <div class="col-md-3">
                    <label>Parcela 1</label>
                    <input type="text" class="form-control" ng-model="editLoanObj.portion1">
                  </div>
                  <div class="col-md-3">
                    <label>Previsão de Pagamento da 1ª Parcela</label>
                    <input type="date" class="form-control" ng-model="editLoanObj.date_p1">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-3">
                    <label>Parcela 2</label>
                    <input type="text" class="form-control" ng-model="editLoanObj.portion2">
                  </div>
                  <div class="col-md-3">
                    <label>Previsão de Pagamento da 2ª Parcela</label>
                    <input type="date" class="form-control" ng-model="editLoanObj.date_p2">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-3">
                    <label>Parcela 3</label>
                    <input type="text" class="form-control" ng-model="editLoanObj.portion3">
                  </div>
                  <div class="col-md-3">
                    <label>Previsão de Pagamento da 3ª Parcela</label>
                    <input type="date" class="form-control" ng-model="editLoanObj.date_p3">
                  </div>
                </div>
              </div>
            </div>
            <div class="box-footer">
              <button class="btn btn-primary" ng-click="submitEditLoan(editLoanObj)">Cadastrar</button>
              <button class="btn btn-danger" ng-click="cancelEditLoan()">Cancelar</button>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <!-- Modal Editar Cliente-->
      <div class="modal fade" id="ExemploModalCentralizadoCliente" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="TituloModalCentralizado">Editar Cliente</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Fechar" ng-click="cancelEditCustomer()">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Nome</p>
              <input type="text" class="form-control" ng-model="customer.name">
              <p>CPF</p>
              <input class="form-control" ng-model="customer.cpf">
              <p>Endereço</p>
              <input class="form-control" ng-model="customer.address">
              <p>Telefone</p>
              <input class="form-control" ng-model="customer.phone">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal" ng-click="cancelEditCustomer()">Fechar</button>
              <button type="button" class="btn btn-primary" ng-click="editSaveCustomer(customer)" data-dismiss="modal">Salvar mudanças</button>
            </div>
          </div>
        </div>
      </div>
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Cliente</h3>
        </div>
        <div class="box-body">
          <table class="table table-striped">
            <tr>
              <th style="width: 10px">#</th>
              <th>Nome</th>
              <th>CPF</th>
              <th>Endereço</th>
              <th>Telefone</th>
              <th>Editar</th>
            </tr>
            <tr style="font-weight: normal">
              <td>1</td>
              <td>{{customer.name}}</td>
              <td>{{customer.cpf}}</td>
              <td>{{customer.address}}</td>
              <td>{{customer.phone}}</td>
              <td>
                <button type="button" class="btn btn-secondary btn" data-toggle="modal" data-target="#ExemploModalCentralizadoCliente" ng-click="editCustomer(customer)")>Editar</button>
                <a href="/customer/{{customer.id}}/destroy" class="btn btn-danger" data-method="delete" data-confirm="Tem certeza que deseja apagar: {{customer.name}}? Todos os emprestimos relacionados a este cliente serão automaticamente deletados.">Apagar</a>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Emprestimo</h3>
        </div>
        <div class="box-body">
          <table class="table table-striped">
            <tr>
              <th style="width: 10px">#</th>
              <th>Loja</th>
              <th>Valor da compra</th>
              <th>1ª Parcela</th>
              <th>2ª Parcela</th>
              <th>3ª Parcela</th>
              <th>Apagar</th>
            </tr>
            <tr ng-repeat="loan in loans" style="font-weight: normal">
              <td>{{$index+1}}</td>
              <td><a href="/loan/{{loan.id}}">{{loan.store}}</a></td>
              <td>R$ {{loan.amount}}</td>
              <td ng-class="redOrGreen(loan.paid_p1)">R$ {{loan.portion1 | number: 2}} ({{loan.date_p1 | date: 'dd/MM/yyyy'}})</td>
              <td ng-class="redOrGreen(loan.paid_p2)">R$ {{loan.portion2 | number: 2}} ({{loan.date_p2 | date: 'dd/MM/yyyy'}})</td>
              <td ng-class="redOrGreen(loan.paid_p3)">R$ {{loan.portion3 | number: 2}} ({{loan.date_p3 | date: 'dd/MM/yyyy'}})</td>
              <td>
                <button type="button" class="btn btn-secondary btn" data-toggle="modal" data-target="#ExemploModalCentralizadoEmprestimo" ng-click="editLoan(loan)")>Editar</button>
                <a href="/loan/{{loan.id}}/delete" data-method="delete" data-confirm="Tem certeza que deseja apagar este emprestimo?" class="btn btn-danger">Apagar</a>
              </td>
            </tr>
          </table>
          <%= link_to 'Voltar', root_path, class:'btn btn-primary btn-sm'%>
          </div>
        </div>
      </div>
    </div>
</section>